[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TMDB_API_KEY = "ea118e768e75a1fe3b53dc99c9e4de09" # Set in Netlify dashboard
