[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TMDB_API_KEY = "your-tmdb-api-key-here" # Set in Netlify dashboard
