[build]
  command = "npm install" # Optional if no build step
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm start" # Optional, adjust if you add a dev script
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
